# Generated by Django 3.1.7 on 2021-03-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_restaurantprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
